Repository Przekol/megak-v2-head-hunter-gr9-backend, pull requests merged in 2023-05, with the labels that each got.

#6 Feature/hh25
  src/app.module.ts
  src/auth/dto/register.dto.ts
  src/hr/dto/create-hr.dto.ts
  src/hr/dto/index.ts
  src/hr/entities/hr.entity.ts
  src/hr/hr.controller.spec.ts
  src/hr/hr.controller.ts
  src/hr/hr.module.ts
  src/hr/hr.service.spec.ts
  src/hr/hr.service.ts
  src/types/hr/hr.request.ts
  src/types/hr/hr.response.ts
  src/types/hr/hr.ts
  src/types/hr/index.ts
  src/types/index.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Ready to Merge

#13 Feature/hh68
  src/admin/admin.service.ts
  src/admin/dto/create-admin.dto.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/auth.swagger.response.ts
  src/auth/dto/register.dto.ts
  src/commands/admin.command.ts
  src/common/filters/global-exceptions.filter.ts
  src/config/index.ts
  src/config/swagger.config.ts
  src/config/validation-pipe.config.ts
  src/hr/dto/create-hr.dto.ts
  src/hr/hr.controller.ts
  src/hr/hr.service.ts
  src/hr/hr.swagger.response.ts
  src/hr/mappers.response.ts
  src/students/student-grades.service.ts
  src/students/students.controller.ts
  src/students/students.swagger.response.ts
  src/tokens/tokens.controller.spec.ts
  src/tokens/tokens.controller.ts
  src/tokens/tokens.module.ts
  src/types/hr/hr.response.ts
  src/users/dto/create-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/utils/csv-file-filter.ts
  src/utils/index.ts
  src/utils/message/mysql-message/mysql-error.message.ts
  src/utils/swagger/common.swagger.responses.ts
  src/utils/swagger/examples/hr.example.ts
  src/utils/swagger/examples/index.ts
  src/utils/swagger/examples/students.example.ts
  src/utils/swagger/examples/unauthorized.example.ts
  src/utils/swagger/examples/users.example.ts
  src/utils/swagger/index.ts
  src/utils/swagger/schemas/hr.schema.ts
  src/utils/swagger/schemas/index.ts
  src/utils/swagger/schemas/response.schema.ts
  src/utils/swagger/schemas/students.schema.ts
  src/utils/swagger/schemas/users.schema.ts
Labels: Ready to Code Review

#12 Feature/hh51 📧
  .example.env
  nest-cli.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/config/env-validation.config.ts
  src/config/event-emitter.config.ts
  src/config/index.ts
  src/config/mailer.config.ts
  src/email/email.module.ts
  src/email/email.service.ts
  src/email/templates/emails/register.hbs
  src/email/templates/emails/restore-pwd.hbs
  src/events/emitters/email.emitter.ts
  src/events/emitters/index.ts
  src/events/events.module.ts
  src/events/events/email/email-registration-link.event.ts
  src/events/events/email/email-registration-links-to-students.event.ts
  src/events/events/email/index.ts
  src/events/events/events.name.ts
  src/events/events/index.ts
  src/events/listeners/email.listener.ts
  src/events/listeners/index.ts
  src/hr/hr.module.ts
  src/hr/hr.service.ts
  src/students/student-grades.service.ts
  src/students/students.module.ts
  src/students/students.service.ts
  src/tokens/links.service.ts
  src/tokens/tokens.module.ts
  src/types/email/email.ts
  src/types/email/index.ts
  src/types/index.ts
  src/types/student-grades/student-grades.ts
  src/types/token/index.ts
  src/types/token/link.ts
  src/utils/index.ts
  src/utils/mail/index.ts
  src/utils/mail/mail-details.ts
Labels: Ready to Code Review

#17 HH84: update types
  src/email/email.service.ts
  src/events/events/email/email-registration-links-to-students.event.ts
  src/students/students.service.ts
  src/tokens/links.service.ts
  src/types/email/email.ts
  src/types/email/index.ts
  src/types/index.ts
  src/types/student-grades/student-grades.response.ts
  src/types/student-grades/student-grades.ts
  src/types/student-profile/student-profile.request.ts
  src/types/student-profile/student-profile.ts
  src/types/student/student.response.ts
  src/types/student/student.ts
  src/utils/mail/mail-details.ts
Labels: Ready to Code Review

#18 Feature/hh81
  src/app.module.ts
  src/main.ts
  src/students/dto/index.ts
  src/students/dto/page-meta.dto.ts
  src/students/dto/page-option.dto.ts
  src/students/dto/page.dto.ts
  src/students/mappers.response.ts
  src/students/students-profiles.service.ts
  src/students/students.controller.ts
  src/students/students.service.ts
  src/students/students.swagger.response.ts
  src/types/student/index.ts
  src/types/student/page-meta-dto-parameters.ts
  src/types/student/student.request.ts
  src/types/student/student.response.ts
  src/types/student/student.ts
  src/utils/constants/index.ts
  src/utils/constants/order.ts
  src/utils/index.ts
  src/utils/swagger/examples/students.example.ts
  src/utils/swagger/schemas/students.schema.ts
Labels: Ready to Code Review, Ready to Merge

#19 Fix/hh88
  src/auth/strategies/local.strategy.ts
  src/common/filters/global-exceptions.filter.ts
Labels: Ready to Merge

#20 Feature/hh87
  README.md
  docker/docker-compose.yaml
  docker/dump/head_hunter.sql
  package.json
Labels: Ready to Code Review, Ready to Merge
